run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert
    - unparam
    - nakedret
    - prealloc
    - gocritic

linters-settings:
  govet:
    enable:
      - shadow
  gofmt:
    simplify: true
  misspell:
    locale: US
  nakedret:
    max-func-lines: 30
  gocritic:
    enabled-tags:
      - diagnostic
      - performance
    disabled-checks:
      - hugeParam
      - paramTypeCombine
      - unnamedResult
      - singleCaseSwitch

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - unparam
    - linters:
        - errcheck
      text: "Error return value of `\\(\\*encoding/json\\.Encoder\\)\\.Encode` is not checked"
    - linters:
        - errcheck
      text: "Error return value of `w\\.Write` is not checked"
